swagger: "2.0"
info:
  description: "Game store api"
  version: "1"
  title: "Swagger game-store"
schemes:
- "https"
- "http"
paths:
  /game:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "query"
        required: false
        type: "string"
      responses:
        "200":
          description: "Ok"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/game_response"
        "401":
          description: "Unauthorized"
    post:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Game object to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/game_request"
      responses:
        "201":
          description: "Created"
          schema:
            $ref: "#/definitions/game_response"
        "400":
          description: "Bad request"
        "401":
          description: "Unauthorized"
  /game/{game_id}:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "game_id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Ok"
          schema:
            $ref: "#/definitions/game_response"
        "401":
          description: "Unauthorized"
        "404":
          description: "Not Found"
    put:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "game_id"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/game_request"
      responses:
        "200":
          description: "Ok"
          schema:
            $ref: "#/definitions/game_response"
        "400":
          description: "Bad request"
        "401":
          description: "Unauthorized"
    delete:
      produces:
      - "application/json"
      parameters:
      - name: "game_id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Ok"
        "401":
          description: "Unauthorized"
        "404":
          description: "Not Found"
  /platform:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "query"
        required: false
        type: "string"
      responses:
        "200":
          description: "Ok"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/platform_response"
        "401":
          description: "Unauthorized"
    post:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/platform_request"
      responses:
        "201":
          description: "Created"
          schema:
            $ref: "#/definitions/platform_response"
        "400":
          description: "Bad request"
        "401":
          description: "Unauthorized"
  /platform/{platform_id}:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "platform_id"
        in: "path"
        description: "ID of platform"
        required: true
        type: "string"
      responses:
        "200":
          description: "Ok"
          schema:
            $ref: "#/definitions/platform_response"
        "401":
          description: "Unauthorized"
        "404":
          description: "Not Found"
    put:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "platform_id"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/platform_request"
      responses:
        "200":
          description: "Ok"
          schema:
            $ref: "#/definitions/platform_response"
        "400":
          description: "Bad request"
        "401":
          description: "Unauthorized"
    delete:
      produces:
      - "application/json"
      parameters:
      - name: "platform_id"
        in: "path"
        description: "ID of platform"
        required: true
        type: "string"
      responses:
        "200":
          description: "Ok"
        "401":
          description: "Unauthorized"
        "404":
          description: "Not Found"
definitions:
  game_request:
    type: "object"
    properties:
      name:
        type: "string"
      description:
        type: "string"
      releaseDate:
        type: "string"
        format: "date"
      price:
        type: "number"
        format: "double"
      availablePlatforms:
        type: "array"
        items:
          type: object
          properties:
            platformId:
              type: "string"
              format: "uuid"
  game_response:
    type: "object"
    properties:
      account:
        type: "string"
      gameId:
        type: "string"
        format: "uuid"
      name:
        type: "string"
      description:
        type: "string"
      releaseDate:
        type: "string"
        format: "date"
      creationDate:
        type: "integer"
        format: "timestamp"
      modificationDate:
        type: "integer"
        format: "timestamp"
      price:
        type: "number"
        format: "double"
      availablePlatforms:
        type: "array"
        items:
          $ref: "#/definitions/platform_response"

  platform_request:
    type: "object"
    properties:
      name:
        type: "string"
      info:
        type: "string"
  platform_response:
    type: "object"
    properties:
      platformId:
        type: "string"
        format: "uuid"
      name:
        type: "string"
      creationDate:
        type: "integer"
        format: "timestamp"
      modificationDate:
        type: "integer"
        format: "timestamp"
      info:
        type: "string"